2025-01-11 14:39:41,573 / WARNING / Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\Python Projects\lesson0\tests_12_4.py", line 22, in test_run
    runner_run = Runner(123)
                 ^^^^^^^^^^^
  File "D:\Python Projects\lesson0\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2025-01-11 14:39:41,579 / WARNING / Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\Python Projects\lesson0\tests_12_4.py", line 12, in test_walk
    runner_walk = Runner('Runner1',-5)
                  ^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Projects\lesson0\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
